name: 'Github Action test publich action custom'
description: 'simple typescript template for building GitHub Actions'
author: 'Sara'
inputs:
  my_input:
    description: 'input description here'
    default: 'World'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "green"
  icon: "bell"  
