name: "Action custom test - marketplace"
on: # rebuild any PRs and main branch changes
  workflow_dispatch: 
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
      - 'releases2/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: action checkout
      uses: actions/checkout@v1
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list
      
    - name: run action
      id: run_action
      #if: ${{ my_input == 'World'}}
      uses: ./
      with: 
        my_input: 'World'

    - name: log action output
      run: echo ${{steps.run_action.outputs.my_output}}  
      
    - name: test echo debug errors
      run: echo "::debug::Debug msg"
    - name: test error type debug
      run: echo "::error::Error msg"
    - name: Test warning msg echo
      run: echo "::warning::warning error"
